export default {
    USER_REGISTER: 'USER_REGISTER',
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAILED: 'USER_REGISTER_FAILED',

    USER_LOGIN: 'USER_LOGIN',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',

    USER_LOGOUT: 'USER_LOGOUT',


    GET_NOTE: 'GET_NOTE',
    GET_NOTE_SUCCESS: 'GET_NOTE_SUCCESS',
    GET_NOTE_FAILED: 'GET_NOTE_FAILED',

    ADD_NOTE: 'ADD_NOTE',
    ADD_NOTE_SUCCESS: 'ADD_NOTE_SUCCESS',
    ADD_NOTE_FAILED: 'ADD_NOTE_FAILED',

    FETCH_NOTE: 'FETCH_NOTE',
    FETCH_NOTE_SUCCESS: 'FETCH_NOTE_SUCCESS',
    FETCH_NOTE_FAILED: 'FETCH_NOTE_FAILED',

    UPDATE_NOTE: 'UPDATE_NOTE',
    UPDATE_NOTE_SUCCESS: 'UPDATE_NOTE_SUCCESS',
    UPDATE_NOTE_FAILED: 'UPDATE_NOTE_FAILED',

    DELETE_NOTE: 'DELETE_NOTE',
    DELETE_NOTE_SUCCESS: 'DELETE_NOTE_SUCCESS',
    DELETE_NOTE_FAILED: 'DELETE_NOTE_FAILED'
}